title: Stan Le Roy
description: IT Student - Mainframe Developer
url: "https://stanleroy.github.io"
baseurl: ""

author:
  name: Stan Le Roy
  email: stan.leroy@student.hogent.be

plugins:
  - jekyll-feed
